#! /bin/sh
bspc rule -r "*"

export PATH=$PATH:/home/xircon/.local/bin/
export QT_QPA_PLATFORMTHEME=qt5ct
xsetroot -cursor_name left_ptr

gap=1
PANEL_HEIGHT=$gap

export gap
export PANEL_HEIGHT

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT))
#bspc config left_padding -$gap
#bspc config left_padding 32
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap

#Various settings
bspc config gapless_monocle false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config borderless_monocle true
#bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

#bspc config window_gap 10

##Color settings
bspc config focused_border_color \#9199ff
bspc config normal_border_color \#000000
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"
bspc config border_width 3

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio 0.5

#bspc monitor -d i ii iii iv v vi vii viii ix x
bspc monitor -d Terminal Emacs Browser Music Five Six Seven Cawbird Settings Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

#bspc monitor -d           

bspc rule -a screenkey --unmanage
bspc rule -a imv state=floating center=true
bspc rule -a spectacle state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a Pcmanfm state=floating center=true rectangle=900x600+0+0
bspc rule -a dolphin state=floating center=true rectangle=900x600+0+0
bspc rule -a Rhythmbox desktop=Music
bspc rule -a rhythmbox desktop=Music
bspc rule -a Deadbeef state=floating rectangle=500x400+1000+400
bspc rule -a Cairo-clock state=floating border=off sticky=on rectangle=130x130+1450+700

bspc rule -a 'Picture in picture' state=floating rectangle=100x30+1483+850

bspc rule -a Emacs state=tiled
bspc rule -a viewnior state=floating center=true
bspc rule -a Cairo-dock state=floating layer=above center=true
bspc rule -a cairo-dock state=floating layer=above center=true
bspc rule -a lxqt-notificationd state=floating layer=above

bspc rule -a Cawbird desktop=8
bspc rule -a Gnome-calendar desktop=Ten
bspc rule -a Cawbird state=floating layer=above rectangle=500x900+0+0 desktop=Cawbird

bspc rule -a mpv state=floating layer=above rectangle=900x506+375+238
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a yad state=floating
bspc rule -a albert layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a dockbarx layer=above
bspc rule -a firefox private=on
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a firefox desktop=III
bspc rule -a Emacs desktop=IV
bspc rule -a korganizer desktop=
bspc rule -a tint2 layer=above border=off state=floating manage=off

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
#bspc config external_rules_command /home/steve/.config/bspwm/external_rules/gsimplecal.sh
bspc config external_rules_command /home/xircon/.config/bspwm/external_rules/gsimplecal.sh

echo steve > tttt&

# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  echo "dummy" > $startup_lock_file
  . ~/.config/bspwm/mybspwm.sh&
fi
